apiVersion: rancher-pipeline/v1
kind: Deployment
metadata:
  name: rancher-pipeline
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rancher-pipeline
        track: stable
    spec:
      containers:
        - name: rancher-pipeline
          image: registry.yykfb.gzpi:5000/rancher-pipeline-demo:v1
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  type: NodePort
  selector:
    app: rancher-pipeline
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088